import './js/customer-review-slider';
import './js/franchise';
import './js/location';
import './js/menu';
import './js/modal-button';
import './js/modal-slider';
import './js/products';
import './js/read-more';
import './js/scrol';